version: '3.6'

services:
  alpine-nginx-php:
    build: .
    image: hackinglab/alpine-nginx-php:3.2
    environment:
    - AUTHOR=e1
    - USERNAME=hracker
    labels:
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:alpine-nginx-php.idocker.hacking-lab.com"
      - "traefik.protocol=http"


