version: '3.4'

services:
  alpine-nginx-php-hobo:
    image: hackinglab/alpine-nginx-php:latest
    hostname: 'hobo'
    environment:
      - "domainname=idocker.REALM_DOMAIN_SUFFIX"
    env_file:
      - ./UUID.env
    volumes:
      - ./UUID.gn:/goldnugget/UUID.gn
    ports:
      - 8000:80

      
